#!/usr/bin/env python3
"""Render a collapsed screenshot gallery into README.md.

Reads ``screenshots/manifest.json`` (produced by
``scripts/screenshot-tour.py``) and rewrites the section between the
HTML markers below in ``README.md``:

    <!-- screenshots:start -->
    ... auto-generated content ...
    <!-- screenshots:end -->

Each tour group becomes a ``<details>`` block grouping its captures.
Images use relative paths so they render both on GitHub and in any
local Markdown viewer that resolves the workspace as the doc root.

Usage:
    scripts/screenshot-readme.py
    scripts/screenshot-readme.py --check    # exit 1 if README would change
    scripts/screenshot-readme.py --readme path/to/README.md \\
        --manifest path/to/manifest.json

Designed to be safe to re-run: if the manifest is missing the script
reports the issue and leaves the README untouched (useful in CI where
we don't ship the .dylib needed to regenerate shots).
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from html import escape
from pathlib import Path

START_MARKER = "<!-- screenshots:start -->"
END_MARKER = "<!-- screenshots:end -->"


def _render_block(manifest: dict) -> str:
    """Build the markdown body that lives between the two markers.

    Layout:
      H3 heading (anchor for cross-doc links)
      One-line summary (count + how to regenerate)
      One <details> per tour group, with an image table inside.
    """
    shots = manifest.get("shots", [])
    if not shots:
        return (
            f"{START_MARKER}\n\n"
            "_No screenshots yet. Run `make screenshots` to generate the gallery._\n\n"
            f"{END_MARKER}\n"
        )

    by_group: dict[str, list[dict]] = defaultdict(list)
    titles: dict[str, str] = {}
    for shot in shots:
        by_group[shot["group"]].append(shot)
        titles.setdefault(shot["group"], shot.get("title", shot["group"]))

    ## Preserve the order in which groups first appear in the manifest
    ## so the gallery follows the tour script's narrative order rather
    ## than alphabetical (alpha would put "audio" before "main").
    seen: list[str] = []
    for shot in shots:
        if shot["group"] not in seen:
            seen.append(shot["group"])

    out: list[str] = [START_MARKER, ""]
    out.append(f"_{len(shots)} captures across {len(seen)} screens. "
               "Generated by `make screenshots && make screenshots-readme`._")
    out.append("")
    for group in seen:
        title = escape(titles[group])
        group_shots = by_group[group]
        out.append(f"<details><summary><strong>{title}</strong> "
                   f"({len(group_shots)} shot{'s' if len(group_shots) != 1 else ''})"
                   "</summary>")
        out.append("")
        for shot in group_shots:
            label = shot["label"]
            ## All three values land inside HTML attributes / element
            ## bodies in the rendered README block. Escape them with
            ## quote=True so a future note containing ``"``, ``<``, or
            ## ``&`` can't break the markup or smuggle HTML in -- the
            ## manifest is generated by us today, but it's a
            ## human-editable JSON file so we shouldn't trust it.
            note = escape(shot.get("note") or label.replace("-", " ").title(),
                          quote=True)
            path = escape(shot["path"], quote=True)
            ## ``screenshots/`` lives at the repo root next to README.md,
            ## so relative paths just work in GitHub's renderer.
            out.append(f"<p><img src=\"screenshots/{path}\" alt=\"{note}\" "
                       f"width=\"360\"><br><sub>{note}</sub></p>")
        out.append("")
        out.append("</details>")
        out.append("")
    out.append(END_MARKER)
    out.append("")
    return "\n".join(out)


def _splice(readme_text: str, block: str) -> str:
    """Replace the existing marker block with ``block`` (which already
    contains both markers). Inserts after the first H1 line if no
    markers exist yet, so the gallery has a sensible default home."""
    start = readme_text.find(START_MARKER)
    end = readme_text.find(END_MARKER)
    if start != -1 and end != -1 and end > start:
        end += len(END_MARKER)
        ## Drop one trailing newline if present so we don't accumulate
        ## blank lines on every regen.
        if end < len(readme_text) and readme_text[end] == "\n":
            end += 1
        return readme_text[:start] + block + readme_text[end:]

    ## No markers yet -- insert after the first blank line following H1.
    lines = readme_text.splitlines(keepends=True)
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("# "):
            insert_at = i + 1
            ## Skip until we hit a blank line, then insert.
            while insert_at < len(lines) and lines[insert_at].strip():
                insert_at += 1
            break
    head = "".join(lines[:insert_at])
    tail = "".join(lines[insert_at:])
    return f"{head}\n## Screenshots\n\n{block}\n{tail}"


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--manifest", type=Path,
                   default=Path("screenshots/manifest.json"))
    p.add_argument("--check", action="store_true",
                   help="exit 1 if README would change (CI-friendly)")
    args = p.parse_args(argv[1:])

    if not args.readme.is_file():
        print(f"!! README not found: {args.readme}", file=sys.stderr)
        return 66
    if not args.manifest.is_file():
        ## In CI we don't have the dylib; skip silently rather than
        ## fail the whole pipeline. The README block already living in
        ## the repo stays as-is.
        print(f">> manifest missing ({args.manifest}); README unchanged.")
        return 0

    manifest = json.loads(args.manifest.read_text())
    block = _render_block(manifest)
    new_readme = _splice(args.readme.read_text(), block)

    current = args.readme.read_text()
    if new_readme == current:
        print(">> README already up to date.")
        return 0

    if args.check:
        print("!! README would change -- run scripts/screenshot-readme.py "
              "to regenerate.", file=sys.stderr)
        return 1

    args.readme.write_text(new_readme)
    print(f">> updated {args.readme} "
          f"({len(manifest.get('shots', []))} shots)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
